[package]
name = "alloca"
version = "0.5.0"
authors = ["Adel Prokurov <adel.prokurov@gmail.com>", "StackOverflowExcept1on"]
edition = "2024"
description = "Safe wrapper around alloca"
documentation = "https://docs.rs/alloca"
readme = "README.md"
repository = "https://github.com/StackOverflowExcept1on/alloca"
license = "MIT"
keywords = ["alloca", "stack-allocation", "vla", "no-std", "memory-management"]
categories = ["memory-management", "api-bindings", "no-std"]

[package.metadata.docs.rs]
features = ["document-features"]

[dependencies]
document-features = { version = "0.2", optional = true }

[build-dependencies]
cc = { version = "1.0", optional = true }

[features]
## Enables compilation of C library `alloca.c` at build time.
compile-alloca = ["dep:cc"]
## Also enables `compile-alloca` and requires suitable C compiler.
## Enables stack-clash protection on non-MSVC targets with `-fstack-clash-protection`.
## Windows MSVC always has stack-clash protection enabled, regardless of this feature.
## Without this feature, non-MSVC targets use `-fno-stack-clash-protection`.
stack-clash-protection = ["compile-alloca"]
## Also enables `compile-alloca` and requires suitable C compiler.
## Enables stack protector support (compiler flag: `-fstack-protector-strong` or `/GS`).
## Without this feature, flag `-fno-stack-protector` or `/GS-` is used.
stack-protector = ["compile-alloca"]
