runs:
  using: composite
  steps:
    - name: Install mingw32 toolchain
      id: msys2
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-i686-gcc
        msystem: MINGW32
        update: true

    - name: Configure mingw32 toolchain
      shell: pwsh
      run: Add-Content $env:GITHUB_PATH '${{ steps.msys2.outputs.msys2-location }}\mingw32\bin'
